[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'


[project]
name = 'text2qti'
description = 'Create quizzes in QTI format from Markdown-based plain text'
readme = 'README.md'
requires-python = '>= 3.10'
authors = [
    {name = 'Geoffrey M. Poore', email = 'gpoore@gmail.com'}
]
license-files = ['LICENSE*', 'CHANGELOG*']
dynamic = ['version']
keywords = [
    'QTI',
    'IMS Question & Test Interoperability',
    'quiz',
    'test',
    'exam',
    'assessment',
    'markdown',
    'LaTeX',
    'plain text',
]
dependencies = [
    'bespon>=0.7.0',
    'markdown>=3.10.2',
]
# https://pypi.python.org/pypi?:action=list_classifiers
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Education',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Topic :: Education :: Testing',
]


[project.optional-dependencies]
dev = ['pytest']


[project.urls]
homepage = 'http://github.com/gpoore/text2qti'
repository = 'http://github.com/gpoore/text2qti'
changelog = 'http://github.com/gpoore/text2qti/blob/master/CHANGELOG.md'


[project.scripts]
text2qti = 'text2qti.cmdline:main'

[project.gui-scripts]
text2qti_tk = 'text2qti.gui.tk:main'


[tool.setuptools]
packages = ['text2qti', 'text2qti.gui']

[tool.setuptools.dynamic]
version = {attr = 'text2qti.__version__'}


[tool.ruff]
line-length = 120
